name: First Workflow

on:
  push:
    branches:
      - main
env:
  PROJECT_NAME: github-actions-practice
jobs:
  pre-job:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        run: echo "Preparation completed"

  build:
    needs: pre-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Show repository files
        run: ls -la

      - name: Print project name
        run: echo "Project is $PROJECT_NAME"
